"""The generation engine.

A deep module: one entry point (``generate_docs``) over a pure core that
resolves declared inputs, hashes them, calls the provider only for sections
whose inputs changed, and writes content-addressed documents atomically.

Regeneration is deterministic and free: the section dependency graph (Phase 6)
plus per-section input hashes decide what to re-render with zero LLM calls.
A second generate with no input changes writes nothing, so the idempotence
gate holds.

No verifier pass. The docs are generated from the scan; they match reality
by construction. ATTENTION.md is an informational note about missing context,
not a human review queue.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any

from autogovern.detect.diff import diff_context, diff_profiles
from autogovern.frameworks import DocumentFeed, Pack, load_pack
from autogovern.generate.frontmatter import (
    build_frontmatter,
    now_iso,
    parse_frontmatter,
    render_document,
)
from autogovern.generate.inputs import (
    compute_section_hash,
    extract_input,
    profile_file_hashes,
)
from autogovern.generate.lockfile import (
    read_context_lock,
    read_lockfile,
    write_context_lock,
    write_lockfile,
)
from autogovern.generate.normalise import normalise_context
from autogovern.generate.prompts import build_section_messages
from autogovern.generate.writer import write_if_changed
from autogovern.ingest import ScannedAgent, ScanResult
from autogovern.models import (
    AgentContext,
    AgentProfile,
    Config,
    ContextManifest,
    NormalisationOutcome,
    NormalisedContext,
)
from autogovern.provider import ProviderClient
from autogovern.versioning import (
    INITIAL_VERSION,
    BumpLevel,
    doc_bump_levels,
    most_significant,
    next_version,
)

GOVERNANCE_DIR = Path("governance")

# Documents generated by the engine without an LLM call. QUICKSTART and
# ATTENTION are non-disableable per the spec.
ENGINE_DOCS_ALWAYS = ["QUICKSTART.md", "ATTENTION.md"]

# LLM-fed documents, in spec table order.
LLM_DOCS = [
    "system-card.md",
    "risk-assessment.md",
    "data-protection.md",
    "oversight.md",
    "inventory.md",
    "testing.md",
    "incident-response.md",
]


@dataclass
class AgentGenerationResult:
    """Outcome of generating docs for one agent."""

    agent_name: str
    agent_slug: str
    governance_dir: Path
    regenerated: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    llm_call_count: int = 0
    written_files: list[Path] = field(default_factory=list)
    pack_version: str = ""
    version_changes: dict[str, tuple[str | None, str, str]] = field(default_factory=dict)
    regeneration_reasons: dict[str, str] = field(default_factory=dict)
    normalisation: NormalisationOutcome | None = None

    @property
    def changed(self) -> bool:
        return bool(self.regenerated)


@dataclass
class GenerationResult:
    """Outcome of a generate run across all agents in a project.

    The project-level result aggregates per-agent results. Token counts and
    LLM call counts sum across agents.
    """

    governance_dir: Path
    per_agent: dict[str, AgentGenerationResult] = field(default_factory=dict)
    pack_version: str = ""
    register_written: bool = False
    written_files: list[Path] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return any(r.changed for r in self.per_agent.values())

    @property
    def regenerated(self) -> list[str]:
        """All regenerated docs across agents, as ``agent/doc`` pairs."""
        return [f"{r.agent_slug}/{doc}" for r in self.per_agent.values() for doc in r.regenerated]

    @property
    def skipped(self) -> list[str]:
        return [f"{r.agent_slug}/{doc}" for r in self.per_agent.values() for doc in r.skipped]

    @property
    def llm_call_count(self) -> int:
        return sum(r.llm_call_count for r in self.per_agent.values())

    @property
    def regeneration_reasons(self) -> dict[str, str]:
        return {
            f"{r.agent_slug}/{doc}": reason
            for r in self.per_agent.values()
            for doc, reason in r.regeneration_reasons.items()
        }

    @property
    def version_changes(self) -> dict[str, tuple[str | None, str, str]]:
        return {
            f"{r.agent_slug}/{doc}": change
            for r in self.per_agent.values()
            for doc, change in r.version_changes.items()
        }


def generate_docs(
    root: Path,
    config: Config,
    scan_result: ScanResult,
    context: ContextManifest,
    *,
    provider: ProviderClient,
    pack: Pack | None = None,
    context_from_file: bool = True,
) -> GenerationResult:
    """Generate or incrementally update governance docs for all agents.

    Writes into ``<root>/governance/``. Each agent gets its own subdirectory
    (``governance/<agent-slug>/``) with its doc set and lockfiles. The project
    level holds ``REGISTER.md``, ``QUICKSTART.md``, ``ATTENTION.md``, and
    ``CHANGELOG.md``.

    Only sections whose input hash changed are re-rendered (one LLM call
    each); the rest are left untouched. Each agent's profile and context
    lockfiles are written on every run (content-addressed, no-op when
    unchanged).

    The provider lifecycle is owned by the caller; this function does not
    close it.
    """
    pack = pack or load_pack()
    governance_dir = root / GOVERNANCE_DIR
    governance_dir.mkdir(parents=True, exist_ok=True)

    result = GenerationResult(governance_dir=governance_dir, pack_version=pack.version)

    for scanned in scan_result.agents:
        agent_result = _generate_for_agent(
            root, governance_dir, config, scanned, context, provider, pack, context_from_file
        )
        result.per_agent[scanned.name] = agent_result
        result.written_files.extend(agent_result.written_files)

    # Project-level docs: register, quickstart, attention, changelog.
    _write_project_docs(governance_dir, config, pack, scan_result, result, context_from_file)
    return result


def _generate_for_agent(
    root: Path,
    governance_dir: Path,
    config: Config,
    scanned: ScannedAgent,
    context: ContextManifest,
    provider: ProviderClient,
    pack: Pack,
    context_from_file: bool,
) -> AgentGenerationResult:
    """Generate docs for one agent into its own governance subdirectory."""
    from autogovern.observability import span as tracing_span

    agent_slug = _slug(scanned.name)
    agent_gov_dir = governance_dir / agent_slug
    agent_gov_dir.mkdir(parents=True, exist_ok=True)

    result = AgentGenerationResult(
        agent_name=scanned.name,
        agent_slug=agent_slug,
        governance_dir=agent_gov_dir,
        pack_version=pack.version,
    )

    profile = scanned.profile
    # Resolve this agent's context (from the manifest's agents dict, or default).
    agent_context = context.agents.get(scanned.name, _default_agent_context())
    # Build a manifest with project + this agent's context for generation.
    agent_manifest = ContextManifest(project=context.project, agents={scanned.name: agent_context})

    file_hashes = profile_file_hashes(profile)
    enabled = _enabled_documents(config)
    timestamp = now_iso()
    bump_levels, changed_fields = _compute_bump_levels(agent_gov_dir, profile, agent_manifest, pack)

    # Normalise this agent's free-text context fields.
    with tracing_span("normalise", attributes={"agent": scanned.name}):
        normalised, normalisation_outcome = normalise_context(
            agent_context, context.project.risk_appetite, provider
        )
    context_for_prompts = _apply_normalisation(agent_manifest, normalised)
    result.normalisation = normalisation_outcome

    for doc in LLM_DOCS:
        if doc not in enabled:
            continue
        feed = pack.document_feeds.get(doc)
        if feed is None:  # pragma: no cover - pack and config should agree
            continue
        _maybe_regenerate_llm_doc(
            agent_gov_dir / doc,
            doc,
            feed,
            profile,
            context_for_prompts,
            provider,
            pack,
            file_hashes,
            result,
            timestamp,
            bump_levels,
            changed_fields,
            agent_name=scanned.name,
        )

    write_lockfile(agent_gov_dir, profile)
    write_context_lock(agent_gov_dir, agent_manifest)
    return result


def _compute_bump_levels(
    governance_dir: Path,
    profile: AgentProfile,
    context: ContextManifest,
    pack: Pack,
) -> tuple[dict[str, BumpLevel] | None, list[str]]:
    """Per-document version bump levels plus changed field names.

    Returns (bump_levels, changed_fields). bump_levels is None on first
    generation (no lockfile); changed_fields is the list of dotted field paths
    that differed between the locked state and current inputs.
    """
    locked_profile = read_lockfile(governance_dir)
    if locked_profile is None:
        return None, []
    diff = diff_profiles(locked_profile, profile)
    locked_context = read_context_lock(governance_dir)
    if locked_context is not None:
        ctx_diff = diff_context(locked_context, context)
        diff.fields.extend(ctx_diff.fields)
    changed_fields = [fd.field for fd in diff.fields]
    return doc_bump_levels(diff.fields, pack.graph), changed_fields


# ---------------------------------------------------------------------------
# LLM-fed documents
# ---------------------------------------------------------------------------


def _maybe_regenerate_llm_doc(
    path: Path,
    doc: str,
    feed: DocumentFeed,
    profile: AgentProfile,
    context: ContextManifest,
    provider: ProviderClient,
    pack: Pack,
    file_hashes: dict[str, str],
    result: AgentGenerationResult,
    timestamp: str,
    bump_levels: dict[str, BumpLevel] | None,
    changed_fields: list[str] | None = None,
    *,
    agent_name: str = "",
) -> None:
    declared = _resolve_declared_inputs(feed, profile, context, agent_name=agent_name)
    new_hash = compute_section_hash(declared, [s.content for s in feed.pack_sections], pack.version)

    existing_fm = _read_frontmatter(path)
    if _section_hash_for(existing_fm, doc) == new_hash and path.is_file():
        result.skipped.append(doc)
        return

    messages = build_section_messages(doc, feed, declared, pack.style_authority)
    from autogovern.observability import span as tracing_span

    span_attrs = {"section": doc, "agent": agent_name} if agent_name else {"section": doc}
    with tracing_span(f"generate.{doc}", attributes=span_attrs):
        body = provider.chat(messages, label=doc)
    result.llm_call_count += 1
    result.regenerated.append(doc)
    result.regeneration_reasons[doc] = _regeneration_reason(doc, feed, existing_fm, changed_fields)

    old_version = _version_string(existing_fm.get("doc_version"))
    new_version, level = _stamped_version(existing_fm.get("doc_version"), doc, bump_levels)
    result.version_changes[doc] = (old_version, new_version, level)

    frontmatter = build_frontmatter(
        doc_version=new_version,
        agent_version=profile.version,
        generated=timestamp,
        generator_version=_generator_version(),
        input_hashes=file_hashes,
        framework_pack_version=pack.version,
        section_hashes={doc: new_hash},
    )
    if write_if_changed(path, render_document(frontmatter, body)):
        result.written_files.append(path)


def _regeneration_reason(
    doc: str,
    feed: DocumentFeed,
    existing_fm: dict[str, Any],
    changed_fields: list[str] | None,
) -> str:
    """Why this document is being regenerated.

    Returns the specific field that changed (if identifiable from the diff and
    the feed's declared inputs), or a general reason (first generation, pack
    content change) when the trigger is structural rather than field-level.
    """
    if not existing_fm or not existing_fm.get("doc_version"):
        return "first generation"
    if not changed_fields:
        return "pack content changed"
    # Intersect the changed fields with this doc's declared inputs.
    declared = set(feed.all_inputs)
    matching = [f for f in changed_fields if f in declared]
    if matching:
        return ", ".join(matching)
    return "input hash changed"


def _apply_normalisation(
    context: ContextManifest, normalised: NormalisedContext
) -> ContextManifest:
    """Return a deep copy of ``context`` with the three enum fields resolved.

    The raw context is preserved for the lockfile and diff; this copy feeds
    section prompts and section hashes so only meaning-changes trigger
    regeneration. The manifest has one agent; that agent's fields are updated.
    """
    agent_name = next(iter(context.agents), "default")
    agent_context = context.agents.get(agent_name, _default_agent_context())
    return context.model_copy(deep=True).model_copy(
        update={
            "project": context.project.model_copy(
                update={"risk_appetite": normalised.risk_appetite.value}
            ),
            "agents": {
                agent_name: agent_context.model_copy(
                    update={
                        "deployment_context": normalised.deployment_context.value,
                        "autonomy_level": normalised.autonomy_level.value,
                    }
                )
            },
        }
    )


def _resolve_declared_inputs(
    feed: DocumentFeed, profile: AgentProfile, context: ContextManifest, agent_name: str = ""
) -> dict[str, object]:
    declared: dict[str, object] = {}
    for path in feed.profile_inputs:
        declared[path] = extract_input(path, profile, context)
    for path in feed.context_inputs:
        # Resolve wildcard context.agents.*.field to the specific agent.
        resolved_path = path
        if path.startswith("context.agents.*.") and agent_name:
            field_name = path.split("*.", 1)[1]
            resolved_path = f"context.agents.{agent_name}.{field_name}"
        declared[path] = extract_input(resolved_path, profile, context)
    return declared


def _read_frontmatter(path: Path) -> dict[str, Any]:
    """Read an existing document's frontmatter, or {} if absent/unparseable."""
    if not path.is_file():
        return {}
    fm, _ = parse_frontmatter(path.read_text(encoding="utf-8"))
    return fm


def _section_hash_for(frontmatter: dict[str, Any], doc: str) -> str | None:
    """The stored section hash for ``doc`` from parsed frontmatter."""
    raw = frontmatter.get("section_hashes", {})
    if not isinstance(raw, dict):
        return None
    value = raw.get(doc)
    return str(value) if value is not None else None


def _version_string(value: object) -> str | None:
    """A frontmatter doc_version as a string, or None when absent."""
    return str(value) if isinstance(value, str) and value else None


def _stamped_version(
    existing: object, doc: str, bump_levels: dict[str, BumpLevel] | None
) -> tuple[str, str]:
    """The (doc_version, level) for a regenerated document.

    First generation (no lockfile) stamps INITIAL_VERSION. Otherwise the doc
    is bumped at its classified level, defaulting to patch when the change
    was not field-classified (e.g. a framework pack content change).
    """
    if bump_levels is None:
        return INITIAL_VERSION, "initial"
    level = bump_levels.get(doc, "patch")
    return next_version(existing, level), level


# ---------------------------------------------------------------------------
# Engine-generated documents
# ---------------------------------------------------------------------------


def _write_project_docs(
    governance_dir: Path,
    config: Config,
    pack: Pack,
    scan_result: ScanResult,
    result: GenerationResult,
    context_from_file: bool,
) -> None:
    """Write the project-level docs: register, quickstart, attention, changelog."""
    timestamp = now_iso()
    common = _Common(
        agent_version="project",
        generator_version=_generator_version(),
        input_hashes={},
        framework_pack_version=pack.version,
    )

    # REGISTER.md: the agent inventory (always written).
    register_body = _register_body(scan_result, result)
    _write_project_doc(
        governance_dir / "REGISTER.md", "REGISTER.md", register_body, timestamp, common, result
    )

    # QUICKSTART: regenerate only if something changed this run.
    if result.changed:
        body = _quickstart_body(scan_result, result, context_from_file)
        _write_project_doc(
            governance_dir / "QUICKSTART.md", "QUICKSTART.md", body, timestamp, common, result
        )

    # ATTENTION: informational note about context completeness.
    att_body = _attention_body(context_from_file)
    _write_project_doc(
        governance_dir / "ATTENTION.md", "ATTENTION.md", att_body, timestamp, common, result
    )

    # CHANGELOG: append-only, one entry per run that regenerated something.
    if result.changed and "CHANGELOG.md" in _enabled_documents(config):
        _append_changelog(governance_dir / "CHANGELOG.md", common, result, timestamp)


def _write_project_doc(
    path: Path,
    doc: str,
    body: str,
    timestamp: str,
    common: _Common,
    result: GenerationResult,
) -> None:
    """Write a project-level document when its body changed."""
    existing_fm = _read_frontmatter(path)
    if existing_fm:
        _, existing_body = parse_frontmatter(path.read_text(encoding="utf-8"))
        if existing_body.lstrip("\n") == body.lstrip("\n"):
            return
    old_version = _version_string(existing_fm.get("doc_version"))
    new_version = INITIAL_VERSION if old_version is None else next_version(old_version, "patch")
    fm = build_frontmatter(
        doc_version=new_version,
        agent_version=common.agent_version,
        generated=timestamp,
        generator_version=common.generator_version,
        input_hashes=common.input_hashes,
        framework_pack_version=common.framework_pack_version,
        section_hashes={doc: _short_hash(body)},
    )
    if write_if_changed(path, render_document(fm, body)):
        result.written_files.append(path)
    result.version_changes[doc] = (old_version, new_version, "patch")


def _register_body(scan_result: ScanResult, result: GenerationResult) -> str:
    """The REGISTER.md body: the project's agent inventory."""
    lines = ["# Agent register", "", "The agents governed in this project.", ""]
    for agent in scan_result.agents:
        slug = _slug(agent.name)
        lines.append(f"## {agent.name}")
        lines.append("")
        lines.append(f"- Root: `{agent.root}`")
        lines.append(f"- Version: {agent.profile.version}")
        lines.append(f"- Docs: `governance/{slug}/`")
        if agent.profile.description:
            lines.append(f"- Description: {agent.profile.description}")
        lines.append("")
    return "\n".join(lines)


def _quickstart_body(
    scan_result: ScanResult, result: GenerationResult, context_from_file: bool
) -> str:
    agent_count = len(scan_result.agents)
    lines = [
        "# Governance quickstart",
        "",
        f"{agent_count} agent(s) governed in this project.",
        "",
        "## What was generated",
        "",
        "The governance document set in this directory was generated by autogovern.",
        "Each agent has its own subdirectory under `governance/`.",
        "",
    ]
    for doc in result.regenerated:
        change = result.version_changes.get(doc)
        if change is not None:
            lines.append(f"- `{doc}` regenerated ({_fmt_version_change(change[0], change[1])})")
        else:
            lines.append(f"- `{doc}` regenerated")
    lines.extend(
        [
            "",
            "## How to read it",
            "",
            "Each document carries YAML frontmatter recording its version, the input",
            "hashes it was built from, and when it was generated.",
            "",
        ]
    )
    if not context_from_file:
        lines.extend(
            [
                "## Note",
                "",
                "Running without a context manifest. Docs are generic. Run",
                "`autogovern init` for specific governance docs.",
                "",
            ]
        )
    return "\n".join(lines)


def _attention_body(context_from_file: bool) -> str:
    """The ATTENTION.md body — informational, not a work queue."""
    if context_from_file:
        return "# Attention ledger\n\nNo attention items. The governance set is fully specified.\n"
    return (
        "# Attention ledger\n\n"
        "Running without a context manifest. Docs are generic. Run "
        "`autogovern init` to provide organisational context (risk appetite, "
        "oversight model, jurisdictions, owner) for specific governance docs.\n"
    )


def _append_changelog(
    path: Path,
    common: _Common,
    result: GenerationResult,
    timestamp: str,
) -> None:
    """Append one entry per regenerating run: date, per-doc version bumps,
    and the most significant change."""
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    _, body_existing = parse_frontmatter(existing) if existing else ({}, "")

    llm_changes = [
        (doc, old, new, level) for doc, (old, new, level) in sorted(result.version_changes.items())
    ]
    bumps = "; ".join(
        f"{doc} ({_fmt_version_change(old, new)})" for doc, old, new, _ in llm_changes
    )
    level = most_significant([lv for _, _, _, lv in llm_changes])
    entry = (
        f"## {timestamp}\n\n"
        f"Regenerated {len(llm_changes)} document(s): {bumps}.\n"
        f"Most significant change: {level}.\n"
    )
    new_body = (body_existing.lstrip("\n") + "\n" + entry) if body_existing.strip() else entry

    old_version = _version_string(_read_frontmatter(path).get("doc_version"))
    new_version = INITIAL_VERSION if old_version is None else next_version(old_version, "patch")
    fm = build_frontmatter(
        doc_version=new_version,
        agent_version=common.agent_version,
        generated=timestamp,
        generator_version=common.generator_version,
        input_hashes=common.input_hashes,
        framework_pack_version=common.framework_pack_version,
        section_hashes={"CHANGELOG.md": _short_hash(new_body)},
    )
    if write_if_changed(path, render_document(fm, new_body)):
        result.written_files.append(path)


def _fmt_version_change(old: str | None, new: str) -> str:
    """Render a version bump for prose: "0.1.0 → 0.2.0", or "new at 0.1.0"."""
    return f"{old} → {new}" if old is not None else f"new at {new}"


def _slug(name: str) -> str:
    """Slugify an agent name for use as a directory name."""
    return name.lower().replace(" ", "-").replace("/", "-").strip(".")


def _default_agent_context() -> AgentContext:
    """The default AgentContext for an agent not in the context manifest."""
    return AgentContext(
        deployment_context="internal",
        autonomy_level="human-in-the-loop",
        intended_users="internal developers",
        oversight_model="human reviews agent outputs before acting on them",
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _Common:
    """The frontmatter fields shared across every engine-generated document."""

    agent_version: str
    generator_version: str
    input_hashes: dict[str, str]
    framework_pack_version: str


def _enabled_documents(config: Config) -> set[str]:
    """The enabled document basenames, QUICKSTART and ATTENTION always on."""
    enabled: set[str] = set()
    name_map = {
        "system-card": "system-card.md",
        "risk-assessment": "risk-assessment.md",
        "data-protection": "data-protection.md",
        "oversight": "oversight.md",
        "inventory": "inventory.md",
        "testing": "testing.md",
        "incident-response": "incident-response.md",
        "changelog": "CHANGELOG.md",
    }
    for key, on in config.documents.items():
        if on:
            enabled.add(name_map.get(key, key))
    enabled.update(ENGINE_DOCS_ALWAYS)
    return enabled


def _short_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


@lru_cache(maxsize=1)
def _generator_version() -> str:
    """The tool version, read once and cached."""
    try:
        from importlib.metadata import version

        return version("autogovern")
    except Exception:  # pragma: no cover - dev installs without metadata
        return "0.0.0+dev"


__all__ = [
    "ENGINE_DOCS_ALWAYS",
    "GOVERNANCE_DIR",
    "LLM_DOCS",
    "GenerationResult",
    "generate_docs",
]
