"""The generation engine.

A deep module: one entry point (``generate_docs``) over a pure core that
resolves declared inputs, hashes them, calls the provider only for sections
whose inputs changed, and writes content-addressed documents atomically.

Regeneration is deterministic and free: the section dependency graph (Phase 6)
plus per-section input hashes decide what to re-render with zero LLM calls.
A second generate with no input changes writes nothing, so the idempotence
gate holds.

No verifier pass. The docs are generated from the scan; they match reality
by construction. ATTENTION.md is an informational note about missing context,
not a human review queue.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any

from autogovern.detect.diff import diff_context, diff_profiles
from autogovern.frameworks import DocumentFeed, Pack, load_pack
from autogovern.generate.frontmatter import (
    build_frontmatter,
    now_iso,
    parse_frontmatter,
    render_document,
)
from autogovern.generate.inputs import (
    compute_section_hash,
    extract_input,
    profile_file_hashes,
)
from autogovern.generate.lockfile import (
    read_context_lock,
    read_lockfile,
    write_context_lock,
    write_lockfile,
)
from autogovern.generate.prompts import build_section_messages
from autogovern.generate.writer import write_if_changed
from autogovern.models import (
    AgentProfile,
    Config,
    ContextManifest,
    MaterialityResult,
)
from autogovern.provider import ProviderClient
from autogovern.versioning import (
    INITIAL_VERSION,
    BumpLevel,
    doc_bump_levels,
    most_significant,
    next_version,
)

GOVERNANCE_DIR = Path("governance")

# Documents generated by the engine without an LLM call. QUICKSTART and
# ATTENTION are non-disableable per the spec.
ENGINE_DOCS_ALWAYS = ["QUICKSTART.md", "ATTENTION.md"]

# LLM-fed documents, in spec table order.
LLM_DOCS = [
    "system-card.md",
    "risk-assessment.md",
    "data-protection.md",
    "oversight.md",
    "inventory.md",
    "testing.md",
    "incident-response.md",
]


@dataclass
class GenerationResult:
    """Outcome of a generate run, for the CLI to print and tests to assert."""

    governance_dir: Path
    regenerated: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    llm_call_count: int = 0
    written_files: list[Path] = field(default_factory=list)
    pack_version: str = ""
    # doc -> (old doc_version or None, new doc_version, bump level)
    version_changes: dict[str, tuple[str | None, str, str]] = field(default_factory=dict)

    @property
    def changed(self) -> bool:
        return bool(self.regenerated)


def generate_docs(
    root: Path,
    config: Config,
    profile: AgentProfile,
    context: ContextManifest,
    *,
    provider: ProviderClient,
    pack: Pack | None = None,
    context_from_file: bool = True,
    materiality: MaterialityResult | None = None,
) -> GenerationResult:
    """Generate or incrementally update the governance document set.

    Writes into ``<root>/governance/``. Only sections whose input hash changed
    are re-rendered (one LLM call each); the rest are left untouched. The
    profile and context lockfiles are written on every run (content-addressed,
    so a no-op when unchanged).

    Each regenerated document's ``doc_version`` is semver-bumped according to
    the significance of the change that caused it (see
    :mod:`autogovern.versioning`); first generation stamps ``0.1.0``.

    When ``context_from_file`` is False (vanilla mode), ATTENTION.md notes
    that docs are generic because no context manifest was loaded.

    ``materiality`` is the detection result when regeneration follows a
    ``check --fix``; it is recorded in the changelog entry. None means the
    run was not scored (plain ``generate``).

    The provider lifecycle is owned by the caller; this function does not
    close it.
    """
    pack = pack or load_pack()
    governance_dir = root / GOVERNANCE_DIR
    governance_dir.mkdir(parents=True, exist_ok=True)

    result = GenerationResult(governance_dir=governance_dir, pack_version=pack.version)
    file_hashes = profile_file_hashes(profile)
    enabled = _enabled_documents(config)
    timestamp = now_iso()
    bump_levels = _compute_bump_levels(governance_dir, profile, context, pack)

    for doc in LLM_DOCS:
        if doc not in enabled:
            continue
        feed = pack.document_feeds.get(doc)
        if feed is None:  # pragma: no cover - pack and config should agree
            continue
        _maybe_regenerate_llm_doc(
            governance_dir / doc,
            doc,
            feed,
            profile,
            context,
            provider,
            pack,
            file_hashes,
            result,
            timestamp,
            bump_levels,
        )

    _write_engine_docs(
        governance_dir, config, pack, profile, result, timestamp, context_from_file, materiality
    )
    write_lockfile(governance_dir, profile)
    write_context_lock(governance_dir, context)
    return result


def _compute_bump_levels(
    governance_dir: Path,
    profile: AgentProfile,
    context: ContextManifest,
    pack: Pack,
) -> dict[str, BumpLevel] | None:
    """Per-document version bump levels, or None on first generation.

    Diffs the locked state (profile + context) against the current inputs and
    classifies each affected document via the dependency graph. None means no
    lockfile exists, so every document starts at ``0.1.0``.
    """
    locked_profile = read_lockfile(governance_dir)
    if locked_profile is None:
        return None
    diff = diff_profiles(locked_profile, profile)
    locked_context = read_context_lock(governance_dir)
    if locked_context is not None:
        ctx_diff = diff_context(locked_context, context)
        diff.fields.extend(ctx_diff.fields)
    return doc_bump_levels(diff.fields, pack.graph)


# ---------------------------------------------------------------------------
# LLM-fed documents
# ---------------------------------------------------------------------------


def _maybe_regenerate_llm_doc(
    path: Path,
    doc: str,
    feed: DocumentFeed,
    profile: AgentProfile,
    context: ContextManifest,
    provider: ProviderClient,
    pack: Pack,
    file_hashes: dict[str, str],
    result: GenerationResult,
    timestamp: str,
    bump_levels: dict[str, BumpLevel] | None,
) -> None:
    declared = _resolve_declared_inputs(feed, profile, context)
    new_hash = compute_section_hash(declared, [s.content for s in feed.pack_sections], pack.version)

    existing_fm = _read_frontmatter(path)
    if _section_hash_for(existing_fm, doc) == new_hash and path.is_file():
        result.skipped.append(doc)
        return

    messages = build_section_messages(doc, feed, declared, pack.style_authority)
    body = provider.chat(messages)
    result.llm_call_count += 1
    result.regenerated.append(doc)

    old_version = _version_string(existing_fm.get("doc_version"))
    new_version, level = _stamped_version(existing_fm.get("doc_version"), doc, bump_levels)
    result.version_changes[doc] = (old_version, new_version, level)

    frontmatter = build_frontmatter(
        doc_version=new_version,
        agent_version=profile.version,
        generated=timestamp,
        generator_version=_generator_version(),
        input_hashes=file_hashes,
        framework_pack_version=pack.version,
        section_hashes={doc: new_hash},
    )
    if write_if_changed(path, render_document(frontmatter, body)):
        result.written_files.append(path)


def _resolve_declared_inputs(
    feed: DocumentFeed, profile: AgentProfile, context: ContextManifest
) -> dict[str, object]:
    declared: dict[str, object] = {}
    for path in feed.profile_inputs:
        declared[path] = extract_input(path, profile, context)
    for path in feed.context_inputs:
        declared[path] = extract_input(path, profile, context)
    return declared


def _read_frontmatter(path: Path) -> dict[str, Any]:
    """Read an existing document's frontmatter, or {} if absent/unparseable."""
    if not path.is_file():
        return {}
    fm, _ = parse_frontmatter(path.read_text(encoding="utf-8"))
    return fm


def _section_hash_for(frontmatter: dict[str, Any], doc: str) -> str | None:
    """The stored section hash for ``doc`` from parsed frontmatter."""
    raw = frontmatter.get("section_hashes", {})
    if not isinstance(raw, dict):
        return None
    value = raw.get(doc)
    return str(value) if value is not None else None


def _version_string(value: object) -> str | None:
    """A frontmatter doc_version as a string, or None when absent."""
    return str(value) if isinstance(value, str) and value else None


def _stamped_version(
    existing: object, doc: str, bump_levels: dict[str, BumpLevel] | None
) -> tuple[str, str]:
    """The (doc_version, level) for a regenerated document.

    First generation (no lockfile) stamps INITIAL_VERSION. Otherwise the doc
    is bumped at its classified level, defaulting to patch when the change
    was not field-classified (e.g. a framework pack content change).
    """
    if bump_levels is None:
        return INITIAL_VERSION, "initial"
    level = bump_levels.get(doc, "patch")
    return next_version(existing, level), level


# ---------------------------------------------------------------------------
# Engine-generated documents
# ---------------------------------------------------------------------------


def _write_engine_docs(
    governance_dir: Path,
    config: Config,
    pack: Pack,
    profile: AgentProfile,
    result: GenerationResult,
    timestamp: str,
    context_from_file: bool,
    materiality: MaterialityResult | None,
) -> None:
    file_hashes = profile_file_hashes(profile)
    common = _Common(
        agent_version=profile.version,
        generator_version=_generator_version(),
        input_hashes=file_hashes,
        framework_pack_version=pack.version,
    )

    # QUICKSTART: regenerate only if something changed this run.
    if result.changed:
        body = _quickstart_body(profile, result, context_from_file)
        _write_engine_doc(
            governance_dir / "QUICKSTART.md", "QUICKSTART.md", body, timestamp, common, result
        )

    # ATTENTION: informational note about context completeness.
    att_body = _attention_body(context_from_file)
    _write_engine_doc(
        governance_dir / "ATTENTION.md", "ATTENTION.md", att_body, timestamp, common, result
    )

    # CHANGELOG: append-only, one entry per run that regenerated something.
    # Disableable via config.documents (QUICKSTART and ATTENTION are not).
    if result.changed and "CHANGELOG.md" in _enabled_documents(config):
        _append_changelog(governance_dir / "CHANGELOG.md", common, result, timestamp, materiality)


def _write_engine_doc(
    path: Path,
    doc: str,
    body: str,
    timestamp: str,
    common: _Common,
    result: GenerationResult,
) -> None:
    """Write an engine-generated document when its body changed.

    Comparing bodies (not full content) means an unchanged engine doc keeps
    its existing frontmatter and ``generated`` timestamp, which is what makes
    a no-op generate produce zero git diff. A rewrite bumps ``doc_version``
    by one patch step; the section hash is the body hash (decoupled from the
    version).
    """
    existing_fm = _read_frontmatter(path)
    if existing_fm:
        _, existing_body = parse_frontmatter(path.read_text(encoding="utf-8"))
        if existing_body.lstrip("\n") == body.lstrip("\n"):
            return
    old_version = _version_string(existing_fm.get("doc_version"))
    new_version = INITIAL_VERSION if old_version is None else next_version(old_version, "patch")
    fm = build_frontmatter(
        doc_version=new_version,
        agent_version=common.agent_version,
        generated=timestamp,
        generator_version=common.generator_version,
        input_hashes=common.input_hashes,
        framework_pack_version=common.framework_pack_version,
        section_hashes={doc: _short_hash(body)},
    )
    if write_if_changed(path, render_document(fm, body)):
        result.written_files.append(path)
    result.version_changes[doc] = (old_version, new_version, "patch")


def _quickstart_body(
    profile: AgentProfile, result: GenerationResult, context_from_file: bool
) -> str:
    lines = [
        f"# Governance quickstart for {profile.name}",
        "",
        f"Agent version: {profile.version}",
        "",
        "## What was generated",
        "",
        "The governance document set in this directory was generated by autogovern.",
        "",
    ]
    for doc in result.regenerated:
        change = result.version_changes.get(doc)
        if change is not None:
            lines.append(f"- `{doc}` regenerated ({_fmt_version_change(change[0], change[1])})")
        else:
            lines.append(f"- `{doc}` regenerated")
    lines.extend(
        [
            "",
            "## How to read it",
            "",
            "Each document carries YAML frontmatter recording its version, the input",
            "hashes it was built from, and when it was generated.",
            "",
        ]
    )
    if not context_from_file:
        lines.extend(
            [
                "## Note",
                "",
                "Running without a context manifest. Docs are generic. Run",
                "`autogovern init` for specific governance docs.",
                "",
            ]
        )
    return "\n".join(lines)


def _attention_body(context_from_file: bool) -> str:
    """The ATTENTION.md body — informational, not a work queue."""
    if context_from_file:
        return "# Attention ledger\n\nNo attention items. The governance set is fully specified.\n"
    return (
        "# Attention ledger\n\n"
        "Running without a context manifest. Docs are generic. Run "
        "`autogovern init` to provide organisational context (risk appetite, "
        "oversight model, jurisdictions, owner) for specific governance docs.\n"
    )


def _append_changelog(
    path: Path,
    common: _Common,
    result: GenerationResult,
    timestamp: str,
    materiality: MaterialityResult | None,
) -> None:
    """Append one entry per regenerating run: date, agent version, per-doc
    version bumps, the most significant change, and the materiality score
    (or "not scored" for a plain generate)."""
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    _, body_existing = parse_frontmatter(existing) if existing else ({}, "")

    llm_changes = [
        (doc, old, new, level)
        for doc, (old, new, level) in sorted(result.version_changes.items())
        if doc in LLM_DOCS
    ]
    bumps = "; ".join(
        f"{doc} ({_fmt_version_change(old, new)})" for doc, old, new, _ in llm_changes
    )
    level = most_significant([lv for _, _, _, lv in llm_changes])
    score = f"{materiality.score} ({materiality.band})" if materiality is not None else "not scored"
    entry = (
        f"## {timestamp} — agent v{common.agent_version}\n\n"
        f"Regenerated {len(llm_changes)} document(s): {bumps}.\n"
        f"Most significant change: {level}. Materiality: {score}.\n"
    )
    new_body = (body_existing.lstrip("\n") + "\n" + entry) if body_existing.strip() else entry

    old_version = _version_string(_read_frontmatter(path).get("doc_version"))
    new_version = INITIAL_VERSION if old_version is None else next_version(old_version, "patch")
    fm = build_frontmatter(
        doc_version=new_version,
        agent_version=common.agent_version,
        generated=timestamp,
        generator_version=common.generator_version,
        input_hashes=common.input_hashes,
        framework_pack_version=common.framework_pack_version,
        section_hashes={"CHANGELOG.md": _short_hash(new_body)},
    )
    if write_if_changed(path, render_document(fm, new_body)):
        result.written_files.append(path)


def _fmt_version_change(old: str | None, new: str) -> str:
    """Render a version bump for prose: "0.1.0 → 0.2.0", or "new at 0.1.0"."""
    return f"{old} → {new}" if old is not None else f"new at {new}"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _Common:
    """The frontmatter fields shared across every engine-generated document."""

    agent_version: str
    generator_version: str
    input_hashes: dict[str, str]
    framework_pack_version: str


def _enabled_documents(config: Config) -> set[str]:
    """The enabled document basenames, QUICKSTART and ATTENTION always on."""
    enabled: set[str] = set()
    name_map = {
        "system-card": "system-card.md",
        "risk-assessment": "risk-assessment.md",
        "data-protection": "data-protection.md",
        "oversight": "oversight.md",
        "inventory": "inventory.md",
        "testing": "testing.md",
        "incident-response": "incident-response.md",
        "changelog": "CHANGELOG.md",
    }
    for key, on in config.documents.items():
        if on:
            enabled.add(name_map.get(key, key))
    enabled.update(ENGINE_DOCS_ALWAYS)
    return enabled


def _short_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


@lru_cache(maxsize=1)
def _generator_version() -> str:
    """The tool version, read once and cached."""
    try:
        from importlib.metadata import version

        return version("autogovern")
    except Exception:  # pragma: no cover - dev installs without metadata
        return "0.0.0+dev"


__all__ = [
    "ENGINE_DOCS_ALWAYS",
    "GOVERNANCE_DIR",
    "LLM_DOCS",
    "GenerationResult",
    "generate_docs",
]
