"""The generation engine.

A deep module: one entry point (``generate_docs``) over a pure core that
resolves declared inputs, hashes them, calls the provider only for sections
whose inputs changed, and writes content-addressed documents atomically.

Regeneration is deterministic and free: the section dependency graph (Phase 6)
plus per-section input hashes decide what to re-render with zero LLM calls.
A second generate with no input changes writes nothing, so the idempotence
gate holds.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path

from autogovern.frameworks import DocumentFeed, Pack, load_pack
from autogovern.generate.frontmatter import (
    build_frontmatter,
    existing_section_hashes,
    now_iso,
    parse_frontmatter,
    render_document,
)
from autogovern.generate.inputs import (
    compute_section_hash,
    extract_input,
    profile_file_hashes,
)
from autogovern.generate.ledger import (
    LEDGER_FILENAME,
    AttentionLedger,
    stable_item_id,
)
from autogovern.generate.lockfile import write_lockfile
from autogovern.generate.prompts import build_section_messages
from autogovern.generate.writer import write_if_changed
from autogovern.models import (
    AgentProfile,
    AttentionItem,
    Config,
    ContextManifest,
    DataCategory,
    VerifierResult,
)
from autogovern.provider import ProviderClient
from autogovern.verify import (
    SectionVerification,
    remove_unsupported_claims,
    to_manifest_result,
    verify_section,
)

GOVERNANCE_DIR = Path("governance")

# Documents generated by the engine without an LLM call. QUICKSTART and
# ATTENTION are non-disableable per the spec.
ENGINE_DOCS_ALWAYS = ["QUICKSTART.md", "ATTENTION.md"]
ENGINE_DOC_CHANGELOG = "CHANGELOG.md"

# LLM-fed documents, in spec table order.
LLM_DOCS = [
    "system-card.md",
    "risk-assessment.md",
    "data-protection.md",
    "oversight.md",
    "inventory.md",
    "testing.md",
    "incident-response.md",
]


@dataclass
class GenerationResult:
    """Outcome of a generate run, for the CLI to print and tests to assert."""

    governance_dir: Path
    regenerated: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    llm_call_count: int = 0
    verifier_call_count: int = 0
    written_files: list[Path] = field(default_factory=list)
    pack_version: str = ""
    verifier_results: list[VerifierResult] = field(default_factory=list)
    attention_items: list[AttentionItem] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.regenerated)


def generate_docs(
    root: Path,
    config: Config,
    profile: AgentProfile,
    context: ContextManifest,
    *,
    provider: ProviderClient,
    pack: Pack | None = None,
) -> GenerationResult:
    """Generate or incrementally update the governance document set.

    Writes into ``<root>/governance/``. Only sections whose input hash changed
    are re-rendered (one LLM call each); the rest are left untouched. The
    profile lockfile is written on every run (content-addressed, so a no-op
    when the profile is unchanged).

    The provider lifecycle is owned by the caller; this function does not
    close it.
    """
    pack = pack or load_pack()
    governance_dir = root / GOVERNANCE_DIR
    governance_dir.mkdir(parents=True, exist_ok=True)

    result = GenerationResult(governance_dir=governance_dir, pack_version=pack.version)
    file_hashes = profile_file_hashes(profile)
    enabled = _enabled_documents(config)

    # Load the existing attention ledger so items persist and close across runs.
    ledger = _load_ledger(governance_dir)
    timestamp = now_iso()

    for doc in LLM_DOCS:
        if doc not in enabled:
            continue
        feed = pack.document_feeds.get(doc)
        if feed is None:  # pragma: no cover - pack and config should agree
            continue
        _maybe_regenerate_llm_doc(
            governance_dir / doc,
            doc,
            feed,
            profile,
            context,
            provider,
            pack,
            file_hashes,
            result,
            ledger,
            timestamp,
        )

    # Generation-time gaps (e.g. scan finds data but context declares none).
    _detect_generation_gaps(profile, context, ledger, timestamp, result)

    _write_engine_docs(governance_dir, config, pack, profile, result, ledger, timestamp)
    write_lockfile(governance_dir, profile)
    return result


# ---------------------------------------------------------------------------
# LLM-fed documents
# ---------------------------------------------------------------------------


def _maybe_regenerate_llm_doc(
    path: Path,
    doc: str,
    feed: DocumentFeed,
    profile: AgentProfile,
    context: ContextManifest,
    provider: ProviderClient,
    pack: Pack,
    file_hashes: dict[str, str],
    result: GenerationResult,
    ledger: AttentionLedger,
    timestamp: str,
) -> None:
    declared = _resolve_declared_inputs(feed, profile, context)
    new_hash = compute_section_hash(declared, [s.content for s in feed.pack_sections], pack.version)

    existing_hash = _existing_hash(path, doc)
    if existing_hash == new_hash and path.is_file():
        result.skipped.append(doc)
        return

    messages = build_section_messages(doc, feed, declared, pack.style_authority)
    body = provider.chat(messages)
    result.llm_call_count += 1
    result.regenerated.append(doc)

    # Verifier pass: check claims, remove unsupported ones, open ledger items.
    body = _verify_and_clean(
        doc, body, feed, declared, file_hashes, provider, pack, result, ledger, timestamp
    )

    frontmatter = build_frontmatter(
        doc_version=_short_hash(new_hash),
        agent_version=profile.version,
        generated=timestamp,
        generator_version=_generator_version(),
        input_hashes=file_hashes,
        framework_pack_version=pack.version,
        section_hashes={doc: new_hash},
    )
    if write_if_changed(path, render_document(frontmatter, body)):
        result.written_files.append(path)


def _resolve_declared_inputs(
    feed: DocumentFeed, profile: AgentProfile, context: ContextManifest
) -> dict[str, object]:
    declared: dict[str, object] = {}
    for path in feed.profile_inputs:
        declared[path] = extract_input(path, profile, context)
    for path in feed.context_inputs:
        declared[path] = extract_input(path, profile, context)
    return declared


def _existing_hash(path: Path, doc: str) -> str | None:
    if not path.is_file():
        return None
    return existing_section_hashes(path.read_text(encoding="utf-8")).get(doc)


# ---------------------------------------------------------------------------
# Engine-generated documents
# ---------------------------------------------------------------------------


def _write_engine_docs(
    governance_dir: Path,
    config: Config,
    pack: Pack,
    profile: AgentProfile,
    result: GenerationResult,
    ledger: AttentionLedger,
    timestamp: str,
) -> None:
    file_hashes = profile_file_hashes(profile)
    common = _Common(
        agent_version=profile.version,
        generator_version=_generator_version(),
        input_hashes=file_hashes,
        framework_pack_version=pack.version,
    )

    # QUICKSTART: regenerate only if something changed this run.
    if result.changed:
        body = _quickstart_body(profile, result)
        fm = _engine_frontmatter("QUICKSTART", _short_hash(body), timestamp, common)
        if _write_engine_doc_if_body_changed(governance_dir / "QUICKSTART.md", fm, body):
            result.written_files.append(governance_dir / "QUICKSTART.md")

    # ATTENTION: written from the ledger on every run.
    att_path = governance_dir / LEDGER_FILENAME
    att_content = ledger.to_markdown(
        generated=timestamp,
        agent_version=profile.version,
        generator_version=common.generator_version,
        framework_pack_version=pack.version,
        input_hashes=file_hashes,
    )
    # The ledger body (not frontmatter) is what changes; compare bodies so
    # an unchanged ledger keeps its existing timestamp (idempotence).
    _fm_existing, existing_body = (
        parse_frontmatter(att_path.read_text(encoding="utf-8")) if att_path.is_file() else ({}, "")
    )
    _, new_body = parse_frontmatter(att_content)
    if (
        new_body.lstrip("\n") != existing_body.lstrip("\n") or not att_path.is_file()
    ) and write_if_changed(att_path, att_content):
        result.written_files.append(att_path)

    # CHANGELOG: append-only, one entry per run that regenerated something.
    if result.changed:
        _append_changelog(governance_dir / "CHANGELOG.md", common, result, timestamp)


def _write_engine_doc_if_body_changed(
    path: Path, frontmatter: dict[str, object], body: str
) -> bool:
    """Write only if the body differs from the existing file's body.

    Comparing bodies (not full content) means an unchanged engine doc keeps
    its existing frontmatter and ``generated`` timestamp, which is what makes
    a no-op generate produce zero git diff.
    """
    if path.is_file():
        _, existing_body = parse_frontmatter(path.read_text(encoding="utf-8"))
        if existing_body.lstrip("\n") == body.lstrip("\n"):
            return False
    return write_if_changed(path, render_document(frontmatter, body))


def _quickstart_body(profile: AgentProfile, result: GenerationResult) -> str:
    lines = [
        f"# Governance quickstart for {profile.name}",
        "",
        f"Agent version: {profile.version}",
        "",
        "## What was generated",
        "",
        "The governance document set in this directory was generated by autogovern.",
        "",
    ]
    for doc in result.regenerated:
        lines.append(f"- `{doc}` regenerated")
    lines.extend(
        [
            "",
            "## How to read it",
            "",
            "Each document carries YAML frontmatter recording its version, the input",
            "hashes it was built from, and when it was generated. `ATTENTION.md` is the",
            "single file to check for anything requiring human action.",
            "",
        ]
    )
    return "\n".join(lines)


def _append_changelog(
    path: Path, common: _Common, result: GenerationResult, timestamp: str
) -> None:
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    _fm_existing, body_existing = parse_frontmatter(existing) if existing else ({}, "")
    entry = f"## {timestamp} — regenerated: {', '.join(result.regenerated)}\n"
    new_body = (body_existing.lstrip("\n") + "\n" + entry) if body_existing.strip() else entry
    fm = _engine_frontmatter("CHANGELOG", _short_hash(new_body), timestamp, common)
    if write_if_changed(path, render_document(fm, new_body)):
        result.written_files.append(path)


# ---------------------------------------------------------------------------
# Verifier and ledger integration
# ---------------------------------------------------------------------------


def _verify_and_clean(
    doc: str,
    body: str,
    feed: DocumentFeed,
    declared: dict[str, object],
    file_hashes: dict[str, str],
    provider: ProviderClient,
    pack: Pack,
    result: GenerationResult,
    ledger: AttentionLedger,
    timestamp: str,
) -> str:
    """Run the verifier, strip unsupported claims, open ledger items.

    Rubric findings are collected on the result for the run manifest; they
    never appear in the document body. Returns the cleaned body.
    """
    verification: SectionVerification = verify_section(
        doc, body, feed, declared, file_hashes, provider, pack
    )
    result.verifier_call_count += 1

    # Record the verifier result for the run manifest (Phase 12).
    section, supported, unsupported, findings = to_manifest_result(verification)
    result.verifier_results.append(
        VerifierResult(
            section=section,
            supported_claims=supported,
            unsupported_claims=unsupported,
            findings=findings,
        )
    )

    unsupported_claims = verification.unsupported_claims
    if unsupported_claims:
        body = remove_unsupported_claims(body, [c.claim for c in unsupported_claims])
        for claim in unsupported_claims:
            resolving = claim.resolving_input or "unknown input"
            detail = claim.claim or "unsupported claim"
            ledger.open_item(
                section=doc,
                detail=detail,
                resolving_input=resolving,
                timestamp=timestamp,
            )
            result.attention_items.append(
                AttentionItem(
                    item_id=stable_item_id(doc, resolving),
                    action="open",
                    detail=f"{doc}: {detail}",
                )
            )
    else:
        # All claims supported: close any previously open items for this section.
        closed = ledger.close_section(doc, timestamp)
        for _ in range(closed):
            result.attention_items.append(AttentionItem(item_id="", action="close", detail=doc))
    return body


def _load_ledger(governance_dir: Path) -> AttentionLedger:
    """Read the existing ATTENTION.md, or return an empty ledger."""
    path = governance_dir / LEDGER_FILENAME
    if not path.is_file():
        return AttentionLedger()
    return AttentionLedger.from_markdown(path.read_text(encoding="utf-8"))


def _detect_generation_gaps(
    profile: AgentProfile,
    context: ContextManifest,
    ledger: AttentionLedger,
    timestamp: str,
    result: GenerationResult,
) -> None:
    """Route generation-time gaps to the ledger.

    The spec's example: the scanner finds data categories in code but the
    context manifest declares none. Each gap opens an attention item naming
    the init/scan input that would resolve it.
    """
    scan_categories = {
        c for c in profile.governance.data_categories.value if c != DataCategory.NONE
    }
    context_categories = {c for c in context.data_categories if c != DataCategory.NONE}
    if scan_categories and not context_categories:
        resolving = "context.data_categories"
        detail = (
            f"scan found data categories {[c.value for c in scan_categories]} "
            f"but context declares none"
        )
        ledger.open_item(
            section="data-protection.md",
            detail=detail,
            resolving_input=resolving,
            timestamp=timestamp,
        )
        result.attention_items.append(
            AttentionItem(
                item_id=stable_item_id("data-protection.md", resolving),
                action="open",
                detail=detail,
            )
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _Common:
    """The frontmatter fields shared across every engine-generated document."""

    agent_version: str
    generator_version: str
    input_hashes: dict[str, str]
    framework_pack_version: str


def _engine_frontmatter(
    doc: str, doc_version: str, generated: str, common: _Common
) -> dict[str, object]:
    return build_frontmatter(
        doc_version=doc_version,
        agent_version=common.agent_version,
        generated=generated,
        generator_version=common.generator_version,
        input_hashes=common.input_hashes,
        framework_pack_version=common.framework_pack_version,
        section_hashes={doc: doc_version},
    )


def _enabled_documents(config: Config) -> set[str]:
    """The enabled document basenames, QUICKSTART and ATTENTION always on."""
    enabled: set[str] = set()
    name_map = {
        "system-card": "system-card.md",
        "risk-assessment": "risk-assessment.md",
        "data-protection": "data-protection.md",
        "oversight": "oversight.md",
        "inventory": "inventory.md",
        "testing": "testing.md",
        "incident-response": "incident-response.md",
        "changelog": "CHANGELOG.md",
    }
    for key, on in config.documents.items():
        if on:
            enabled.add(name_map.get(key, key))
    enabled.update(ENGINE_DOCS_ALWAYS)
    return enabled


def _short_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


def _generator_version() -> str:
    """The tool version, read once and cached."""
    try:
        from importlib.metadata import version

        return version("autogovern")
    except Exception:  # pragma: no cover - dev installs without metadata
        return "0.0.0+dev"


__all__ = [
    "ENGINE_DOCS_ALWAYS",
    "GOVERNANCE_DIR",
    "LLM_DOCS",
    "GenerationResult",
    "generate_docs",
]
